### PR TITLE
clean up .vscode file and add it to .gitignore

### PR DESCRIPTION
**Pull request by jcstang**
Jean, thanks for letting me try out this pull request thing.

### CODE REVIEW

**Comment by JeanPeel** [comment]
Cool, it looks like you made a few minor changes?  If you have any ideas or suggestions please let me know!  I would love feedback.

**Comment by jcstang** [comment]
Ya just little stuff. Hopefully there is a button somewhere on this page that you can merge the proposed changes I have and then that way it will show up in YOUR master branch. super cool!

**Comment by JeanPeel** [comment]
Ok I merged it.  I just wanted to confirm that that is what it was.

**Comment by JeanPeel** [comment]
Jacob, I put in a drop down menu, using bootstrap, that shows up on the media call of the smallest size of screen.  But when I click on it the drop down items do not show up.   Do you know why that is not working?  Is that something I need to code in myself?  Thanks!

**Comment by jcstang** [comment]
@JeanPeel I will have to look at that for you. What did you want it to look like?

**Pull request merged**
